### ISSUE TITLE
error when trying to run v1.2.1 exe holocure trainer

### ISSUE THREAD

**Issue by pixelsdude** [AUSTIN2526/holocure-trainer#7]
Traceback (most recent call last):
  File "app.py", line 129, in <module>
    w = AppWindow()
  File "app.py", line 14, in __init__
    self.ui.setupUi(self)
  File "UI.py", line 38, in setupUi
    page.setWindowTitle(self.UI_text[self.language]['ui_name'])
KeyError: 'en_US'

**Comment by megax99999** [comment]
ya same problem for me QQ

**Comment by megax99999** [comment]
Traceback (most recent call last):
  File "app.py", line 129, in <module>
    w = AppWindow()
  File "app.py", line 14, in __init__
    self.ui.setupUi(self)
  File "UI.py", line 38, in setupUi
    page.setWindowTitle(self.UI_text[self.language]['ui_name'])
KeyError: 'en_MY'

**Comment by AUSTIN2526** [comment]
Wait for me and i'll fix this right away

**Comment by AUSTIN2526** [comment]
I have fixed it
